image: docker:20.10

variables:
  # See https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-enabled-in-kubernetes
  # When using dind service, you must instruct Docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket.
  DOCKER_HOST: tcp://docker:2376
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/services/#accessing-the-services.
  # If you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2376 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2376
  #
  # Specify to Docker where to create the certificates. Docker
  # creates them automatically on boot, and creates
  # `/certs/client` to share between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"
  # These are usually specified by the entrypoint, however the
  # Kubernetes executor doesn't run entrypoints
  # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4125
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_PRIVATE_REPO: repo.irtsysx.fr:5086

services:
  - docker:20.10-dind

stages:
  - build
  - trigger_cd

before_script:
  - docker info

after_script:
  - docker image prune --all --force

build_image:
  stage: build
  script:
    - echo "$NEXUS_PWD" | docker login $DOCKER_PRIVATE_REPO --username $NEXUS_USER --password-stdin
    - docker image build --tag $DOCKER_PRIVATE_REPO/confiance/docusaurus:latest .
    - docker push $DOCKER_PRIVATE_REPO/confiance/docusaurus:latest
  only:
    - master

build_image_tag:
  stage: build
  script:
    - echo "$NEXUS_PWD" | docker login $DOCKER_PRIVATE_REPO --username $NEXUS_USER --password-stdin
    - docker image build --tag $DOCKER_PRIVATE_REPO/confiance/docusaurus:${CI_COMMIT_TAG} .
    - docker tag $DOCKER_PRIVATE_REPO/confiance/docusaurus:${CI_COMMIT_TAG} $DOCKER_PRIVATE_REPO/confiance/docusaurus:latest
    - docker push $DOCKER_PRIVATE_REPO/confiance/docusaurus:${CI_COMMIT_TAG}
    - docker push $DOCKER_PRIVATE_REPO/confiance/docusaurus:latest
  only:
    - tags

trigger:
  stage: trigger_cd
  script:
    - apk update && apk add curl
    - 'curl -s
      -X POST
      -F token=${CI_JOB_TOKEN}
      -F ref=master
      -F "variables[TRIGGERER_PIPELINE_ID]=${CI_PIPELINE_ID}"
      -F "variables[CLUSTER_ENVIRONMENT]=prod"
      -F "variables[DEPLOY_DOCUSAURUS]=true"
      https://git.irt-systemx.fr/api/v4/projects/3726/trigger/pipeline'
  only:
    - tags
    - master
