---
# defaults file for roles/kubernetes

kubernetes_prerequisites_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - lsb-release
  - bridge-utils
  - gpg

kubernetes_version: 1.29.1-1.1