apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "icescrum-chart.fullname" . }}
  labels:
    {{- include "icescrum-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "icescrum-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "icescrum-chart.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: icescrum-storage-pvc
        persistentVolumeClaim:
          claimName: icescrum-storage-pvc
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "icescrum-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
          - name: ICESCRUM_CONTEXT
            value: /
          volumeMounts:
          - mountPath: /root
            name: icescrum-storage-pvc
